version: "3.8"
services:
  postgres:
    container_name: red-book-postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: redbook
      PGDATA: /data/postgres
    volumes:
      - .docker-data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - rb-net
    restart: unless-stopped

  pgadmin:
    container_name: red-book-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@k.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - .docker-data/pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - rb-net
    restart: unless-stopped

networks:
  rb-net:
    driver: bridge
