# Generated by Django 5.0.3 on 2024-04-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='sp_type',
            field=models.CharField(default='UCL', max_length=25),
            preserve_default=False,
        ),
    ]
